/*
  Set any config.h overrides for your specific keymap here.
  See config.h options at https://docs.qmk.fm/#/config_options?id=the-configh-file
*/
/* TAPPING_TERM=175 */

/* /\* MOUSEKEY_INTERVAL=16 *\/ */
/* MOUSEKEY_DELAY=0 */
/* MOUSEKEY_TIME_TO_MAX=60 */
/* MOUSEKEY_MAX_SPEED=7 */
/* MOUSEKEY_WHEEL_DELAY=0 */

#undef MOUSEKEY_INTERVAL
#undef MOUSEKEY_DELAY
#undef MOUSEKEY_TIME_TO_MAX
#undef MOUSEKEY_MAX_SPEED
#undef MOUSEKEY_WHEEL_DELAY
#undef MOUSEKEY_WHEEL_INTERVAL
#undef MOUSEKEY_WHEEL_MAX_SPEED
#undef MOUSEKEY_WHEEL_TIME_TO_MAX

#define MOUSEKEY_INTERVAL 10
#define MOUSEKEY_DELAY 0
#define MOUSEKEY_TIME_TO_MAX 20
#define MOUSEKEY_MAX_SPEED 2
#define MOUSEKEY_WHEEL_DELAY 0
#define MOUSEKEY_WHEEL_INTERVAL 25
#define MOUSEKEY_WHEEL_MAX_SPEED 20
#define MOUSEKEY_WHEEL_TIME_TO_MAX 150

#define LEADER_PER_KEY_TIMING
#undef LEADER_TIMEOUT
#define LEADER_TIMEOUT 666

#define UNICODE_SELECTED_MODES UC_LNX